package protection

// Country represents a country for the UI selector
type Country struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

// GetCountries returns all countries for the UI selector
func GetCountries() []Country {
	return []Country{
		{Code: "AF", Name: "Afghanistan"},
		{Code: "AL", Name: "Albania"},
		{Code: "DZ", Name: "Algeria"},
		{Code: "AD", Name: "Andorra"},
		{Code: "AO", Name: "Angola"},
		{Code: "AR", Name: "Argentina"},
		{Code: "AM", Name: "Armenia"},
		{Code: "AU", Name: "Australia"},
		{Code: "AT", Name: "Austria"},
		{Code: "AZ", Name: "Azerbaijan"},
		{Code: "BH", Name: "Bahrain"},
		{Code: "BD", Name: "Bangladesh"},
		{Code: "BY", Name: "Belarus"},
		{Code: "BE", Name: "Belgium"},
		{Code: "BZ", Name: "Belize"},
		{Code: "BJ", Name: "Benin"},
		{Code: "BT", Name: "Bhutan"},
		{Code: "BO", Name: "Bolivia"},
		{Code: "BA", Name: "Bosnia"},
		{Code: "BW", Name: "Botswana"},
		{Code: "BR", Name: "Brazil"},
		{Code: "BN", Name: "Brunei"},
		{Code: "BG", Name: "Bulgaria"},
		{Code: "BF", Name: "Burkina Faso"},
		{Code: "BI", Name: "Burundi"},
		{Code: "KH", Name: "Cambodia"},
		{Code: "CM", Name: "Cameroon"},
		{Code: "CA", Name: "Canada"},
		{Code: "CL", Name: "Chile"},
		{Code: "CN", Name: "China"},
		{Code: "CO", Name: "Colombia"},
		{Code: "CD", Name: "Congo (DRC)"},
		{Code: "CR", Name: "Costa Rica"},
		{Code: "HR", Name: "Croatia"},
		{Code: "CU", Name: "Cuba"},
		{Code: "CY", Name: "Cyprus"},
		{Code: "CZ", Name: "Czech Republic"},
		{Code: "DK", Name: "Denmark"},
		{Code: "DJ", Name: "Djibouti"},
		{Code: "DO", Name: "Dominican Rep."},
		{Code: "EC", Name: "Ecuador"},
		{Code: "EG", Name: "Egypt"},
		{Code: "SV", Name: "El Salvador"},
		{Code: "EE", Name: "Estonia"},
		{Code: "ET", Name: "Ethiopia"},
		{Code: "FI", Name: "Finland"},
		{Code: "FR", Name: "France"},
		{Code: "GA", Name: "Gabon"},
		{Code: "GE", Name: "Georgia"},
		{Code: "DE", Name: "Germany"},
		{Code: "GH", Name: "Ghana"},
		{Code: "GR", Name: "Greece"},
		{Code: "GT", Name: "Guatemala"},
		{Code: "GN", Name: "Guinea"},
		{Code: "HT", Name: "Haiti"},
		{Code: "HN", Name: "Honduras"},
		{Code: "HK", Name: "Hong Kong"},
		{Code: "HU", Name: "Hungary"},
		{Code: "IS", Name: "Iceland"},
		{Code: "IN", Name: "India"},
		{Code: "ID", Name: "Indonesia"},
		{Code: "IR", Name: "Iran"},
		{Code: "IQ", Name: "Iraq"},
		{Code: "IE", Name: "Ireland"},
		{Code: "IL", Name: "Israel"},
		{Code: "IT", Name: "Italy"},
		{Code: "JM", Name: "Jamaica"},
		{Code: "JP", Name: "Japan"},
		{Code: "JO", Name: "Jordan"},
		{Code: "KZ", Name: "Kazakhstan"},
		{Code: "KE", Name: "Kenya"},
		{Code: "KW", Name: "Kuwait"},
		{Code: "KG", Name: "Kyrgyzstan"},
		{Code: "LA", Name: "Laos"},
		{Code: "LV", Name: "Latvia"},
		{Code: "LB", Name: "Lebanon"},
		{Code: "LY", Name: "Libya"},
		{Code: "LT", Name: "Lithuania"},
		{Code: "LU", Name: "Luxembourg"},
		{Code: "MO", Name: "Macau"},
		{Code: "MK", Name: "N. Macedonia"},
		{Code: "MG", Name: "Madagascar"},
		{Code: "MY", Name: "Malaysia"},
		{Code: "ML", Name: "Mali"},
		{Code: "MT", Name: "Malta"},
		{Code: "MX", Name: "Mexico"},
		{Code: "MD", Name: "Moldova"},
		{Code: "MN", Name: "Mongolia"},
		{Code: "ME", Name: "Montenegro"},
		{Code: "MA", Name: "Morocco"},
		{Code: "MZ", Name: "Mozambique"},
		{Code: "MM", Name: "Myanmar"},
		{Code: "NA", Name: "Namibia"},
		{Code: "NP", Name: "Nepal"},
		{Code: "NL", Name: "Netherlands"},
		{Code: "NZ", Name: "New Zealand"},
		{Code: "NI", Name: "Nicaragua"},
		{Code: "NE", Name: "Niger"},
		{Code: "NG", Name: "Nigeria"},
		{Code: "NO", Name: "Norway"},
		{Code: "OM", Name: "Oman"},
		{Code: "PK", Name: "Pakistan"},
		{Code: "PA", Name: "Panama"},
		{Code: "PY", Name: "Paraguay"},
		{Code: "PE", Name: "Peru"},
		{Code: "PH", Name: "Philippines"},
		{Code: "PL", Name: "Poland"},
		{Code: "PT", Name: "Portugal"},
		{Code: "QA", Name: "Qatar"},
		{Code: "RO", Name: "Romania"},
		{Code: "RU", Name: "Russia"},
		{Code: "RW", Name: "Rwanda"},
		{Code: "SA", Name: "Saudi Arabia"},
		{Code: "SN", Name: "Senegal"},
		{Code: "RS", Name: "Serbia"},
		{Code: "SG", Name: "Singapore"},
		{Code: "SK", Name: "Slovakia"},
		{Code: "SI", Name: "Slovenia"},
		{Code: "SO", Name: "Somalia"},
		{Code: "ZA", Name: "South Africa"},
		{Code: "KR", Name: "South Korea"},
		{Code: "ES", Name: "Spain"},
		{Code: "LK", Name: "Sri Lanka"},
		{Code: "SD", Name: "Sudan"},
		{Code: "SE", Name: "Sweden"},
		{Code: "CH", Name: "Switzerland"},
		{Code: "SY", Name: "Syria"},
		{Code: "TW", Name: "Taiwan"},
		{Code: "TJ", Name: "Tajikistan"},
		{Code: "TZ", Name: "Tanzania"},
		{Code: "TH", Name: "Thailand"},
		{Code: "TN", Name: "Tunisia"},
		{Code: "TR", Name: "Turkey"},
		{Code: "TM", Name: "Turkmenistan"},
		{Code: "UG", Name: "Uganda"},
		{Code: "UA", Name: "Ukraine"},
		{Code: "AE", Name: "UAE"},
		{Code: "GB", Name: "United Kingdom"},
		{Code: "US", Name: "United States"},
		{Code: "UY", Name: "Uruguay"},
		{Code: "UZ", Name: "Uzbekistan"},
		{Code: "VE", Name: "Venezuela"},
		{Code: "VN", Name: "Vietnam"},
		{Code: "YE", Name: "Yemen"},
		{Code: "ZM", Name: "Zambia"},
		{Code: "ZW", Name: "Zimbabwe"},
	}
}
