// This is the curated fallback vocabulary, committed so the package always
// compiles. Run tools/genwords to replace it with the much larger WordNet-derived
// lists:
//
//	go run ./tools/genwords -adj dict/index.adj -noun dict/index.noun -blocklist blocklist.txt

package namegen

var adjectives = []string{
	"able", "active", "adept", "agile", "airy", "alert", "alive", "alpha", "amber",
	"ample", "ancient", "arctic", "ardent", "artful", "astral", "autumn", "azure",
	"balmy", "bold", "bonny", "brave", "breezy", "briny", "brisk", "bright", "broad",
	"bronze", "bubbly", "burly", "busy",
	"calm", "candid", "canny", "casual", "chilly", "chosen", "civic", "classic",
	"clean", "clear", "clever", "cloudy", "coastal", "cobalt", "cosmic", "cozy",
	"crimson", "crisp", "crystal", "curious", "cyan",
	"dainty", "dandy", "dapper", "daring", "deep", "deft", "dense", "desert", "dewy",
	"digital", "divine", "dizzy", "dreamy", "driven", "dusky", "dusty",
	"eager", "early", "earthy", "easy", "elated", "electric", "elegant", "emerald",
	"endless", "epic", "equal", "eternal", "exact", "expert",
	"faint", "fair", "famed", "fancy", "fast", "feisty", "fertile", "fiery", "fine",
	"firm", "flat", "fleet", "floral", "fluent", "flying", "fond", "formal", "frank",
	"free", "fresh", "frosty", "funky", "fuzzy",
	"gallant", "gentle", "giant", "gifted", "gilded", "glad", "gleaming", "glossy",
	"golden", "graceful", "grand", "grassy", "great", "groovy",
	"handy", "happy", "hardy", "harmonic", "hazy", "hearty", "heavy", "hidden",
	"high", "honest", "hopeful", "humble", "hushed",
	"icy", "ideal", "idle", "inner", "iron", "ivory",
	"jagged", "jaunty", "jolly", "jovial", "joyful", "jumbo",
	"keen", "kind", "kinetic",
	"lasting", "late", "lazy", "leafy", "legal", "level", "light", "lilac", "limber",
	"linen", "little", "lively", "lofty", "logical", "lone", "long", "loud", "loyal",
	"lucid", "lucky", "lunar", "lush",
	"magic", "main", "major", "mellow", "merry", "metric", "mighty", "mild", "misty",
	"mobile", "modern", "modest", "molten", "moral", "mossy", "mute", "mystic",
	"narrow", "native", "natural", "neat", "neon", "nervy", "nifty", "nimble",
	"noble", "normal", "novel", "nutty",
	"oaken", "only", "open", "ornate", "outer", "oval",
	"pacific", "pale", "patient", "peachy", "perfect", "phantom", "pink", "placid",
	"plain", "plush", "polar", "polished", "precise", "pretty", "prime", "prized",
	"proper", "proud", "pure", "purple",
	"quaint", "quantum", "quick", "quiet", "quirky",
	"radiant", "rapid", "rare", "ready", "real", "regal", "rich", "right", "rigid",
	"ripe", "robust", "rocky", "rosy", "royal", "rugged", "rural", "rustic",
	"safe", "salty", "sandy", "satin", "scarlet", "secret", "serene", "sharp",
	"sheer", "shiny", "short", "silent", "silken", "silver", "simple", "sincere",
	"single", "sleek", "slender", "slim", "smart", "smooth", "snowy", "soft",
	"solar", "solid", "sonic", "sound", "spare", "sparkling", "spicy", "spiral",
	"splendid", "square", "stable", "starry", "steady", "steel", "stellar", "stern",
	"still", "stout", "straight", "strong", "sturdy", "subtle", "sudden", "sunny",
	"super", "supple", "sure", "sweet", "swift",
	"tall", "tame", "tender", "thankful", "thermal", "thick", "thrifty", "tidal",
	"tidy", "timely", "tiny", "total", "tranquil", "trim", "tropic", "true",
	"trusty", "twin",
	"ultra", "unique", "united", "upbeat", "upper", "urban", "useful",
	"valiant", "vast", "velvet", "verdant", "vibrant", "vital", "vivid", "vocal",
	"warm", "wary", "watery", "wavy", "wealthy", "western", "whole", "wide", "wild",
	"willing", "windy", "wise", "witty", "wooden", "woolly", "worthy",
	"yearly", "young",
	"zany", "zesty", "zippy",
}

var nouns = []string{
	"acorn", "alcove", "almond", "anchor", "anthem", "apple", "arbor", "arch",
	"arrow", "ash", "aspen", "atlas", "aurora", "avenue",
	"badge", "banner", "basin", "bay", "beacon", "beam", "bear", "beech", "bell",
	"berry", "birch", "bison", "blossom", "bluff", "bolt", "book", "border",
	"boulder", "branch", "breeze", "bridge", "brook", "buffalo", "burrow", "butte",
	"cabin", "cactus", "camp", "canal", "candle", "canyon", "cape", "cardinal",
	"cascade", "castle", "cavern", "cedar", "chalk", "chapel", "charm", "cherry",
	"chestnut", "chime", "cliff", "cloud", "clover", "coast", "cobble", "comet",
	"compass", "coral", "cove", "crane", "crater", "creek", "crest", "crow",
	"cypress",
	"dahlia", "daisy", "dale", "dawn", "deer", "delta", "dew", "dial", "diamond",
	"dock", "dolphin", "dome", "door", "dove", "dragon", "dream", "drift", "dune",
	"dusk",
	"eagle", "earth", "echo", "eddy", "elk", "elm", "ember", "emblem", "engine",
	"estuary", "ether",
	"falcon", "fawn", "feather", "fern", "ferry", "field", "finch", "fjord",
	"flame", "flare", "flint", "flower", "flute", "forge", "fountain", "fox",
	"frost",
	"garden", "gate", "gem", "geyser", "glacier", "glade", "glen", "globe", "glow",
	"gopher", "gorge", "grain", "grape", "grove", "gulf", "gull",
	"harbor", "harvest", "hawk", "haven", "heather", "hedge", "heron", "hill",
	"hollow", "honey", "horizon", "hummock", "hut",
	"ibis", "inlet", "iris", "isle", "ivy",
	"jasmine", "jetty", "jewel", "journey", "juniper",
	"kestrel", "key", "kite", "knoll",
	"lagoon", "lake", "lamp", "lantern", "larch", "lark", "laurel", "leaf", "ledge",
	"lemon", "lily", "linden", "lion", "log", "lotus", "lynx",
	"magnolia", "marsh", "meadow", "mesa", "mill", "mist", "moon", "moor", "moss",
	"mountain", "mouse", "mulberry",
	"nectar", "needle", "nest", "nettle", "night", "nook", "north", "nova",
	"oak", "oasis", "ocean", "orbit", "orchard", "orchid", "oriole", "otter", "owl",
	"oyster",
	"palm", "pansy", "paper", "park", "path", "peach", "peak", "pebble", "pelican",
	"petal", "pier", "pine", "planet", "plateau", "plum", "pond", "poppy", "port",
	"puffin",
	"quail", "quarry", "quartz", "quill",
	"rabbit", "rain", "rapids", "raven", "reed", "reef", "ridge", "rill", "ripple",
	"river", "road", "robin", "rock", "rose", "rowan", "rune",
	"sail", "sand", "sapling", "sea", "seal", "season", "sequoia", "shade",
	"shadow", "shale", "shell", "shore", "shrub", "sky", "slate", "sleet", "slope",
	"snow", "sorrel", "spark", "sparrow", "spire", "spruce", "spur", "star",
	"stone", "storm", "stream", "summit", "sun", "sunset", "surf", "swallow",
	"swan",
	"talon", "temple", "thistle", "thorn", "thunder", "tide", "timber", "torch",
	"tower", "trail", "tree", "trout", "tulip", "tundra", "turtle",
	"umber", "umbra", "upland", "urchin",
	"valley", "vale", "vane", "vapor", "vault", "vine", "vista", "volcano",
	"vortex",
	"walnut", "warren", "water", "wave", "willow", "wind", "wing", "wisp", "wolf",
	"wood", "wren",
	"yard", "yarrow", "yew", "yucca",
	"zenith", "zephyr", "zinnia",
}

// shortWords contains common 3-5 character words for compact subdomains
var shortWords = []string{
	// Nature (3-5 chars)
	"ace", "air", "ant", "ape", "arc", "ash", "awe", "axe",
	"bay", "bee", "bid", "bit", "bow", "box", "bud", "bug", "bus",
	"cab", "cam", "cap", "car", "cat", "cob", "cod", "cog", "cow", "cry", "cub", "cup", "cut",
	"dam", "day", "den", "dew", "dig", "dim", "dip", "dog", "dot", "dry", "dub", "dug", "duo",
	"ear", "eat", "eel", "egg", "elk", "elm", "end", "era", "eve", "eye",
	"fan", "far", "fat", "fax", "fed", "fee", "few", "fig", "fin", "fir", "fit", "fix", "fly", "fog", "fox", "fun", "fur",
	"gap", "gas", "gem", "gin", "gnu", "gob", "god", "got", "gum", "gun", "gut", "guy", "gym",
	"ham", "hat", "hay", "hen", "hex", "hid", "hip", "hit", "hob", "hog", "hop", "hot", "how", "hub", "hue", "hug", "hum", "hut",
	"ice", "icy", "ill", "imp", "ink", "inn", "ion", "ire", "irk", "ivy",
	"jab", "jam", "jar", "jaw", "jay", "jet", "jig", "job", "jog", "joy", "jug", "jut",
	"keg", "ken", "key", "kid", "kin", "kit",
	"lab", "lac", "lad", "lag", "lap", "law", "lax", "lay", "lea", "led", "leg", "let", "lid", "lip", "lit", "log", "lot", "low", "lug",
	"mad", "man", "map", "mar", "mat", "max", "may", "men", "met", "mid", "mix", "mob", "mod", "mop", "mud", "mug", "mum",
	"nab", "nag", "nap", "net", "new", "nib", "nil", "nip", "nit", "nod", "nor", "not", "now", "nub", "nun", "nut",
	"oak", "oar", "oat", "odd", "ode", "off", "oft", "ohm", "oil", "old", "one", "opt", "orb", "ore", "our", "out", "owe", "owl", "own",
	"pac", "pad", "pal", "pan", "par", "pas", "pat", "paw", "pay", "pea", "peg", "pen", "pep", "per", "pet", "pew", "pic", "pie", "pig", "pin", "pit", "ply", "pod", "pop", "pot", "pro", "pry", "pub", "pug", "pun", "pup", "put",
	"quo",
	"rag", "ram", "ran", "rap", "rat", "raw", "ray", "red", "ref", "rep", "rib", "rid", "rig", "rim", "rip", "rob", "rod", "roe", "rot", "row", "rub", "rug", "run", "rut", "rye",
	"sac", "sad", "sag", "sap", "sat", "saw", "say", "sea", "set", "sew", "she", "shy", "sin", "sip", "sir", "sis", "sit", "six", "ski", "sky", "sly", "sob", "sod", "son", "sop", "sot", "sow", "soy", "spa", "spy", "sub", "sue", "sum", "sun", "sup",
	"tab", "tad", "tag", "tan", "tap", "tar", "tax", "tea", "ten", "the", "thy", "tic", "tie", "tin", "tip", "toe", "tog", "tom", "ton", "too", "top", "tot", "tow", "toy", "try", "tub", "tug", "tun", "two",
	"ugh", "urn", "use",
	"van", "vat", "vet", "vex", "via", "vie", "vim", "vow",
	"wad", "wag", "war", "was", "wax", "way", "web", "wed", "wee", "wet", "who", "why", "wig", "win", "wit", "wiz", "woe", "wok", "won", "woo", "wow",
	"yak", "yam", "yap", "yaw", "yea", "yen", "yes", "yet", "yew", "yin", "yip", "you", "yow",
	"zag", "zap", "zed", "zee", "zen", "zig", "zip", "zit", "zoo",
	// 4-5 letter words
	"able", "ache", "acid", "aged", "aide", "ally", "also", "alto", "amid", "aqua", "arch", "area", "aria", "atom", "aunt", "auto", "axis",
	"baby", "back", "bake", "ball", "band", "bank", "bark", "barn", "base", "bath", "bead", "beak", "beam", "bean", "bear", "beat", "beef", "bell", "belt", "bend", "bent", "best", "beta", "bike", "bird", "bite", "blow", "blue", "blur", "boat", "body", "bold", "bolt", "bomb", "bond", "bone", "book", "boom", "boot", "born", "boss", "both", "bowl", "brim", "bulk", "bull", "bump", "burn", "bush", "busy", "buzz",
	"cage", "cake", "calm", "came", "camp", "cape", "card", "care", "cart", "case", "cash", "cast", "cave", "cell", "chat", "chef", "chip", "chop", "city", "clam", "clan", "clap", "clay", "clip", "club", "clue", "coal", "coat", "coca", "code", "coin", "cold", "come", "cone", "cook", "cool", "cope", "copy", "cord", "core", "cork", "corn", "cost", "cozy", "crab", "crew", "crop", "crow", "cube", "cult", "curb", "cure", "curl",
	"dale", "dame", "damp", "dare", "dark", "dart", "dash", "data", "date", "dawn", "deal", "dean", "dear", "deck", "deed", "deep", "demo", "dent", "desk", "dial", "dice", "diet", "dime", "dine", "disc", "dish", "disk", "dive", "dock", "dome", "done", "doom", "door", "dorm", "dose", "down", "drab", "drag", "draw", "drip", "drop", "drum", "dual", "duck", "dude", "duel", "duke", "dull", "dumb", "dump", "dune", "dunk", "dusk", "dust", "duty",
	"each", "earn", "ease", "east", "easy", "echo", "edge", "edit", "else", "emit", "envy", "epic", "euro", "even", "ever", "evil", "exam", "exec", "exit", "expo", "eyed",
	"face", "fact", "fade", "fail", "fair", "fake", "fall", "fame", "fang", "fare", "farm", "fast", "fate", "fawn", "fear", "feat", "feed", "feel", "feet", "fell", "felt", "fern", "fest", "file", "fill", "film", "find", "fine", "fire", "firm", "fish", "fist", "five", "flag", "flak", "flat", "flaw", "flea", "fled", "flee", "flex", "flip", "flow", "flux", "foam", "foe", "fold", "folk", "fond", "font", "food", "fool", "foot", "ford", "fore", "fork", "form", "fort", "foul", "four", "fowl", "free", "frog", "from", "fuel", "full", "fume", "fund", "funk", "fuse", "fuss", "fuzz",
	"gain", "gala", "gale", "game", "gang", "garb", "gate", "gave", "gaze", "gear", "germ", "gift", "gild", "girl", "give", "glad", "glen", "glow", "glue", "goal", "goat", "gold", "golf", "gone", "good", "gown", "grab", "grad", "gram", "gray", "grew", "grey", "grid", "grim", "grin", "grip", "grit", "grow", "gulf", "guru", "gust",
	"hack", "hail", "hair", "half", "hall", "halt", "hand", "hang", "hank", "hard", "hare", "harm", "harp", "hash", "haste", "hate", "haul", "have", "hawk", "haze", "hazy", "head", "heal", "heap", "hear", "heat", "heed", "heel", "held", "hell", "helm", "help", "hemp", "herb", "herd", "here", "hero", "hide", "high", "hike", "hill", "hint", "hire", "hold", "hole", "holy", "home", "hood", "hook", "hope", "horn", "host", "hour", "howl", "huge", "hull", "hunk", "hunt", "hurl", "hurt", "hush",
	"icon", "idea", "idle", "idol", "inch", "info", "into", "iron", "isle", "item",
	"jack", "jade", "jail", "jazz", "jean", "jerk", "jest", "join", "joke", "jolt", "judo", "jump", "june", "junk", "jury", "just",
	"kale", "keen", "keep", "kelp", "kept", "kick", "kill", "kind", "king", "kite", "knee", "knew", "knit", "knob", "knot", "know",
	"lace", "lack", "lacy", "lady", "laid", "lake", "lamb", "lame", "lamp", "land", "lane", "lard", "last", "late", "lava", "lawn", "lazy", "lead", "leaf", "leak", "lean", "leap", "left", "lend", "lens", "less", "levy", "liar", "lick", "life", "lift", "like", "lily", "limb", "lime", "limp", "line", "link", "lion", "list", "lite", "live", "load", "loaf", "loan", "lobe", "lock", "loft", "logo", "lone", "long", "look", "loop", "lord", "lore", "lose", "loss", "lost", "loud", "love", "luck", "lump", "lung", "lure", "lurk", "lush", "lust",
	"made", "maid", "mail", "main", "make", "male", "mall", "malt", "many", "mare", "mark", "mars", "mash", "mask", "mass", "mast", "mate", "math", "maze", "meal", "mean", "meat", "meek", "meet", "melt", "memo", "mend", "menu", "mere", "mesh", "mess", "mica", "mild", "mile", "milk", "mill", "mime", "mind", "mine", "mini", "mint", "miss", "mist", "moat", "mock", "mode", "mojo", "mold", "mole", "monk", "mood", "moon", "moor", "more", "moss", "most", "moth", "move", "much", "muck", "mule", "murk", "muse", "mush", "musk", "must", "mute", "myth",
	"nail", "name", "nape", "navy", "near", "neat", "neck", "need", "neon", "nerd", "nest", "news", "next", "nice", "nick", "nine", "node", "none", "noon", "norm", "nose", "note", "noun", "nude",
	"obey", "odds", "ogre", "okay", "omen", "omit", "once", "only", "onto", "onus", "open", "oral", "orca", "oven", "over", "owed",
	"pace", "pack", "pact", "page", "paid", "pail", "pain", "pair", "pale", "palm", "pane", "papa", "park", "part", "pass", "past", "path", "pave", "peak", "pear", "peat", "peck", "peek", "peel", "peer", "pelt", "perk", "perm", "pest", "pick", "pier", "pike", "pile", "pill", "pine", "pink", "pipe", "piss", "pita", "pity", "plan", "play", "plea", "plod", "plot", "plow", "plug", "plum", "plus", "poem", "poet", "poke", "pole", "poll", "polo", "pomp", "pond", "pony", "pool", "poor", "pope", "pork", "port", "pose", "post", "pour", "pray", "prep", "prey", "prim", "prix", "prod", "prom", "prop", "pros", "prow", "puff", "pull", "pulp", "pump", "punk", "pure", "push", "putt",
	"quad", "quit", "quiz",
	"race", "rack", "raft", "rage", "raid", "rail", "rain", "rake", "ramp", "rang", "rank", "rare", "rash", "rate", "rave", "read", "real", "ream", "reap", "rear", "reed", "reef", "reel", "rely", "rend", "rent", "rest", "rice", "rich", "ride", "rift", "rind", "ring", "riot", "ripe", "rise", "risk", "rite", "road", "roam", "roar", "robe", "rock", "rode", "role", "roll", "roof", "room", "root", "rope", "rose", "rosy", "rout", "rove", "ruby", "rude", "ruin", "rule", "rump", "rung", "rush", "rust",
	"sack", "safe", "sage", "said", "sail", "sake", "sale", "salt", "same", "sand", "sane", "sang", "sank", "save", "scan", "scar", "seal", "seam", "seat", "sect", "seed", "seek", "seem", "seen", "self", "sell", "semi", "send", "sent", "sept", "sewn", "shed", "ship", "shop", "shot", "show", "shut", "sick", "side", "sift", "sigh", "sign", "silk", "silo", "sine", "sing", "sink", "site", "size", "slab", "slam", "slap", "slat", "sled", "slid", "slim", "slip", "slit", "slob", "slop", "slot", "slow", "slug", "slum", "smog", "snap", "snip", "snow", "snub", "snug", "soak", "soap", "soar", "sock", "soda", "sofa", "soft", "soil", "sold", "sole", "solo", "some", "song", "soon", "soot", "sore", "sort", "sour", "span", "spar", "spec", "sped", "spin", "spit", "spot", "spun", "spur", "stab", "stag", "star", "stay", "stem", "step", "stew", "stir", "stop", "stow", "stub", "stud", "stun", "such", "suck", "suds", "suit", "sulk", "sung", "sunk", "sure", "surf", "swap", "sway", "swim",
	"tack", "taco", "tact", "tail", "take", "tale", "talk", "tall", "tame", "tank", "tape", "task", "taxi", "team", "tear", "tech", "teem", "teen", "tell", "temp", "tend", "tent", "term", "test", "text", "than", "that", "thaw", "them", "then", "they", "thin", "this", "thud", "thus", "tick", "tide", "tidy", "tier", "tile", "tilt", "time", "tint", "tiny", "tire", "toad", "toil", "told", "toll", "tomb", "tone", "took", "tool", "tops", "tore", "torn", "tort", "toss", "tour", "town", "tram", "trap", "tray", "tree", "trek", "trim", "trio", "trip", "trod", "trot", "true", "tuba", "tube", "tuck", "tuft", "tuna", "tune", "turf", "turn", "tusk", "twig", "twin", "type",
	"ugly", "undo", "unit", "upon", "urge", "used", "user",
	"vain", "vamp", "vary", "vase", "vast", "veal", "veer", "vein", "vent", "verb", "very", "vest", "veto", "vial", "vice", "view", "vine", "visa", "void", "volt", "vote",
	"wade", "wage", "wail", "wait", "wake", "walk", "wall", "wand", "want", "ward", "warm", "warn", "warp", "wart", "wary", "wash", "wasp", "wave", "wavy", "waxy", "weak", "wear", "weed", "week", "weld", "well", "went", "wept", "were", "west", "what", "when", "whim", "whip", "whom", "wick", "wide", "wife", "wild", "will", "wilt", "wimp", "wind", "wine", "wing", "wink", "wipe", "wire", "wise", "wish", "with", "woke", "wolf", "womb", "wood", "wool", "word", "wore", "work", "worm", "worn", "wrap", "wren",
	"yard", "yarn", "yawn", "year", "yell", "yoga", "yoke", "yolk", "your",
	"zany", "zeal", "zero", "zest", "zinc", "zone", "zoom",
}
