// This is the curated fallback vocabulary, committed so the package always
// compiles. Run tools/genwords to replace it with the much larger WordNet-derived
// lists:
//
//	go run ./tools/genwords -adj dict/index.adj -noun dict/index.noun -blocklist blocklist.txt

package namegen

var adjectives = []string{
	"able", "active", "adept", "agile", "airy", "alert", "alive", "alpha", "amber",
	"ample", "ancient", "arctic", "ardent", "artful", "astral", "autumn", "azure",
	"balmy", "bold", "bonny", "brave", "breezy", "briny", "brisk", "bright", "broad",
	"bronze", "bubbly", "burly", "busy",
	"calm", "candid", "canny", "casual", "chilly", "chosen", "civic", "classic",
	"clean", "clear", "clever", "cloudy", "coastal", "cobalt", "cosmic", "cozy",
	"crimson", "crisp", "crystal", "curious", "cyan",
	"dainty", "dandy", "dapper", "daring", "deep", "deft", "dense", "desert", "dewy",
	"digital", "divine", "dizzy", "dreamy", "driven", "dusky", "dusty",
	"eager", "early", "earthy", "easy", "elated", "electric", "elegant", "emerald",
	"endless", "epic", "equal", "eternal", "exact", "expert",
	"faint", "fair", "famed", "fancy", "fast", "feisty", "fertile", "fiery", "fine",
	"firm", "flat", "fleet", "floral", "fluent", "flying", "fond", "formal", "frank",
	"free", "fresh", "frosty", "funky", "fuzzy",
	"gallant", "gentle", "giant", "gifted", "gilded", "glad", "gleaming", "glossy",
	"golden", "graceful", "grand", "grassy", "great", "groovy",
	"handy", "happy", "hardy", "harmonic", "hazy", "hearty", "heavy", "hidden",
	"high", "honest", "hopeful", "humble", "hushed",
	"icy", "ideal", "idle", "inner", "iron", "ivory",
	"jagged", "jaunty", "jolly", "jovial", "joyful", "jumbo",
	"keen", "kind", "kinetic",
	"lasting", "late", "lazy", "leafy", "legal", "level", "light", "lilac", "limber",
	"linen", "little", "lively", "lofty", "logical", "lone", "long", "loud", "loyal",
	"lucid", "lucky", "lunar", "lush",
	"magic", "main", "major", "mellow", "merry", "metric", "mighty", "mild", "misty",
	"mobile", "modern", "modest", "molten", "moral", "mossy", "mute", "mystic",
	"narrow", "native", "natural", "neat", "neon", "nervy", "nifty", "nimble",
	"noble", "normal", "novel", "nutty",
	"oaken", "only", "open", "ornate", "outer", "oval",
	"pacific", "pale", "patient", "peachy", "perfect", "phantom", "pink", "placid",
	"plain", "plush", "polar", "polished", "precise", "pretty", "prime", "prized",
	"proper", "proud", "pure", "purple",
	"quaint", "quantum", "quick", "quiet", "quirky",
	"radiant", "rapid", "rare", "ready", "real", "regal", "rich", "right", "rigid",
	"ripe", "robust", "rocky", "rosy", "royal", "rugged", "rural", "rustic",
	"safe", "salty", "sandy", "satin", "scarlet", "secret", "serene", "sharp",
	"sheer", "shiny", "short", "silent", "silken", "silver", "simple", "sincere",
	"single", "sleek", "slender", "slim", "smart", "smooth", "snowy", "soft",
	"solar", "solid", "sonic", "sound", "spare", "sparkling", "spicy", "spiral",
	"splendid", "square", "stable", "starry", "steady", "steel", "stellar", "stern",
	"still", "stout", "straight", "strong", "sturdy", "subtle", "sudden", "sunny",
	"super", "supple", "sure", "sweet", "swift",
	"tall", "tame", "tender", "thankful", "thermal", "thick", "thrifty", "tidal",
	"tidy", "timely", "tiny", "total", "tranquil", "trim", "tropic", "true",
	"trusty", "twin",
	"ultra", "unique", "united", "upbeat", "upper", "urban", "useful",
	"valiant", "vast", "velvet", "verdant", "vibrant", "vital", "vivid", "vocal",
	"warm", "wary", "watery", "wavy", "wealthy", "western", "whole", "wide", "wild",
	"willing", "windy", "wise", "witty", "wooden", "woolly", "worthy",
	"yearly", "young",
	"zany", "zesty", "zippy",
}

var nouns = []string{
	"acorn", "alcove", "almond", "anchor", "anthem", "apple", "arbor", "arch",
	"arrow", "ash", "aspen", "atlas", "aurora", "avenue",
	"badge", "banner", "basin", "bay", "beacon", "beam", "bear", "beech", "bell",
	"berry", "birch", "bison", "blossom", "bluff", "bolt", "book", "border",
	"boulder", "branch", "breeze", "bridge", "brook", "buffalo", "burrow", "butte",
	"cabin", "cactus", "camp", "canal", "candle", "canyon", "cape", "cardinal",
	"cascade", "castle", "cavern", "cedar", "chalk", "chapel", "charm", "cherry",
	"chestnut", "chime", "cliff", "cloud", "clover", "coast", "cobble", "comet",
	"compass", "coral", "cove", "crane", "crater", "creek", "crest", "crow",
	"cypress",
	"dahlia", "daisy", "dale", "dawn", "deer", "delta", "dew", "dial", "diamond",
	"dock", "dolphin", "dome", "door", "dove", "dragon", "dream", "drift", "dune",
	"dusk",
	"eagle", "earth", "echo", "eddy", "elk", "elm", "ember", "emblem", "engine",
	"estuary", "ether",
	"falcon", "fawn", "feather", "fern", "ferry", "field", "finch", "fjord",
	"flame", "flare", "flint", "flower", "flute", "forge", "fountain", "fox",
	"frost",
	"garden", "gate", "gem", "geyser", "glacier", "glade", "glen", "globe", "glow",
	"gopher", "gorge", "grain", "grape", "grove", "gulf", "gull",
	"harbor", "harvest", "hawk", "haven", "heather", "hedge", "heron", "hill",
	"hollow", "honey", "horizon", "hummock", "hut",
	"ibis", "inlet", "iris", "isle", "ivy",
	"jasmine", "jetty", "jewel", "journey", "juniper",
	"kestrel", "key", "kite", "knoll",
	"lagoon", "lake", "lamp", "lantern", "larch", "lark", "laurel", "leaf", "ledge",
	"lemon", "lily", "linden", "lion", "log", "lotus", "lynx",
	"magnolia", "marsh", "meadow", "mesa", "mill", "mist", "moon", "moor", "moss",
	"mountain", "mouse", "mulberry",
	"nectar", "needle", "nest", "nettle", "night", "nook", "north", "nova",
	"oak", "oasis", "ocean", "orbit", "orchard", "orchid", "oriole", "otter", "owl",
	"oyster",
	"palm", "pansy", "paper", "park", "path", "peach", "peak", "pebble", "pelican",
	"petal", "pier", "pine", "planet", "plateau", "plum", "pond", "poppy", "port",
	"puffin",
	"quail", "quarry", "quartz", "quill",
	"rabbit", "rain", "rapids", "raven", "reed", "reef", "ridge", "rill", "ripple",
	"river", "road", "robin", "rock", "rose", "rowan", "rune",
	"sail", "sand", "sapling", "sea", "seal", "season", "sequoia", "shade",
	"shadow", "shale", "shell", "shore", "shrub", "sky", "slate", "sleet", "slope",
	"snow", "sorrel", "spark", "sparrow", "spire", "spruce", "spur", "star",
	"stone", "storm", "stream", "summit", "sun", "sunset", "surf", "swallow",
	"swan",
	"talon", "temple", "thistle", "thorn", "thunder", "tide", "timber", "torch",
	"tower", "trail", "tree", "trout", "tulip", "tundra", "turtle",
	"umber", "umbra", "upland", "urchin",
	"valley", "vale", "vane", "vapor", "vault", "vine", "vista", "volcano",
	"vortex",
	"walnut", "warren", "water", "wave", "willow", "wind", "wing", "wisp", "wolf",
	"wood", "wren",
	"yard", "yarrow", "yew", "yucca",
	"zenith", "zephyr", "zinnia",
}
